name: Ru python
on:
  push:
  schedule:
  - cron: "1 * * * *"
jobs:
  build:       
    name: env1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run my python
      run:
        python 0714.py
